✨Implement repeatability constraints
Hochfrequenz/ahbicht pull request #136
Opened 2022-02-28 16:15 UTC by schachmett

Will implement repeatability constraints (number range 2000-2499, see image)
See #96 #39 

![test](https://user-images.githubusercontent.com/32598388/155031278-f533c34a-78e9-4514-b35f-b5960bcaf0cb.png)

2022-03-15 09:37 UTC, hf-kklein commented on unittests/test_json_serialization.py
> +                    "repeatability_constraint_keys": ["2001, 2002, 2003"],
@schachmett sicher an der stelle?
```suggestion
                    repeatability_constraint_keys=["2001, 2002, 2003"],
                    package_keys=["17P"],
                ),
                {
                    "hint_keys": ["501", "502", "503"],
                    "format_constraint_keys": ["901", "902"],
                    "requirement_constraint_keys": ["1", "2", "3", "4"],
                    "repeatability_constraint_keys": ["2001", "2002", "2003"],
```

2022-03-15 12:15 UTC, schachmett commented on unittests/test_json_serialization.py
> +                    "repeatability_constraint_keys": ["2001, 2002, 2003"],
Danke für den Hinweis, das war quatsch

2022-03-22 13:21 UTC, hf-kklein requested changes
Hi Simon, könntest du da noch ein paar Unittests für schreiben? Wenn du nen Breakpoint an die angepassten Stellen setzt müsste das recht einfach möglich sein, die Tests zu finden, die an deinem Code vorbeikommen.

Die kannst du dann adaptieren.

2022-03-22 23:14 UTC, schachmett commented
Ich habe meine Testprobleme in VS Code gelöst, kann ich morgen berichten / auf stackoverflow posten.
Jetzt muss ich nur noch die Tests tatsächlich einmal abklappern.

2022-04-25 06:16 UTC, HF-FSteinkamp commented on src/ahbicht/condition_node_distinction.py
>      raise ValueError("Condition key is not in valid number range.")
Kurze Fragen, warum
if Bedingung1:
if Bedingung2:
...
if BedingungX:

Ist mit elif arbeiten an dieser stelle nicht angenehmer und macht den code übersichtlicher?
if Bedingung1:
elif
elif
else
   RaiseError

2022-04-25 06:41 UTC, hf-kklein commented on src/ahbicht/condition_node_distinction.py
>      raise ValueError("Condition key is not in valid number range.")
nein, das würde pylint anmeckern.
Deinem Beispiel fehlt ein Detail. Tatsächlich sieht der Code so aus:

```python
if bedingung1:
    return ...
if bedingung2:
    return
else:
    raise
```

ohne das return hättest du recht.
siehe auch: https://stackoverflow.com/questions/63755912/why-does-pylint-complain-about-unnecessary-elif-after-return-no-else-return

2022-05-04 14:57 UTC, hf-aschloegl approved these changes

2022-05-04 14:57 UTC, hf-aschloegl commented on README.rst
> +| Wiederholbarkeit/RepeatabilityConstraint | - gives minimum and maximum occorrence
```suggestion
| Wiederholbarkeit / RepeatabilityConstraint | - gives minimum and maximum occurence                                                                                                                                                                                                                                                                                                                          | "Segmentgruppe ist mindestens einmal je SG4 IDE+24 (Vorgang) anzugeben"                                 |
```

2022-05-16 07:32 UTC, merged