✨Implement Packages
Hochfrequenz/ahbicht pull request #72
Opened 2021-10-26 14:21 UTC by hf-kklein

fixes #23

## What it does

- Introduces PackageResolver: The base class of all classes that translat a package key (f.e. '123P'->"[1] U ([2] O [3]) to a condition expression (using the PackageKeyConditionExpressionMapping)
- Introduces hardcoded/dictbased Package Resolver

## ̶W̶h̶a̶t̶'̶s̶ ̶s̶t̶i̶l̶l̶ ̶m̶i̶s̶s̶i̶n̶g̶:
- s̶o̶ ̶f̶a̶r̶ ̶w̶e̶ ̶m̶i̶s̶s̶ ̶t̶h̶e̶ ̶p̶o̶s̶s̶i̶b̶i̶l̶i̶t̶y̶ ̶t̶o̶ ̶e̶v̶a̶l̶u̶a̶t̶e̶ ̶a̶ ̶p̶a̶c̶k̶a̶g̶e̶ ̶a̶s̶ ̶a̶ ̶w̶h̶o̶l̶e̶/̶s̶h̶o̶r̶t̶c̶u̶t̶ ̶(̶f̶.̶e̶.̶ ̶"̶1̶2̶3̶P̶"̶-̶>̶F̶u̶l̶f̶i̶l̶l̶e̶d̶)̶ => we won't build this.

2021-11-28 21:16 UTC, hf-kklein commented
#93 might be the missing link

2022-01-27 08:04 UTC, hf-aschloegl requested changes
Die Test schauen soweit ja gut aus, aber ich hatte doch ein paar Schwierigkeiten beim Nachvollziehen. Nachdem die Packages ja wieder ein größerer Baustein sind, könntest du die README und das Ablaufdiagramm anpassen, damit man die Idee dahinter nachvollziehen kann? Mir ist der gedachte Ablauf noch nicht hundertpro klar.
Besonders den einen Punkt den ich auch im Code angemerkt habe, wieso das eine Attribut sowohl die resolved packages, auch auch ihr evaluation result beinhalten sollte.
Vielleicht liegt das auch an der Idee des Shortcuts das Paket auszuwerten ohne es aufzulösen, aber das kannst du ja auch schon im Ablauf beschreiben ;)

Zweiter Punkt, war es Absicht nur die Pakete in der [INT P] Form zu behandeln? Weil oft ist ja auch noch die Wiederholung hinten dran a la [3P0..1].
Und können wir die Grammatik nicht direkt benutzen die Pakete als Pakete zu definieren und weiterzubenutzen, statt später nochmal mit regex oder ähnlichem wieder rauszusammeln?

2022-01-27 10:16 UTC, hf-kklein commented on src/ahbicht/expressions/condition_expression_parser.py
> +    package: "[" INT "P]"
das war mir nicht klar, dass da noch mehr kommt

2022-01-27 10:17 UTC, hf-kklein commented on unittests/test_categorized_key_extraction.py
> +        # json_string = ContentEvaluationResultSchema(many=True).dumps(actual)
ich glaube nur, weil es nicht genutzt wurde.

2022-01-27 10:19 UTC, hf-kklein commented on src/ahbicht/content_evaluation/content_evaluation_result.py
> +    OR to a condition fulfilled value that applies to the entire package.
ja, ich dachte s wäre praktisch. aber es ist in der tat schwieriger zu erklären, warum wir das wollen. und 

> if its hard to explain...

2022-01-28 08:39 UTC, hf-kklein commented on src/ahbicht/content_evaluation/categorized_key_extract.py
> +                packages={},
kommentar ist da.

2022-01-28 08:39 UTC, hf-kklein commented on src/ahbicht/content_evaluation/content_evaluation_result.py
> +    OR to a condition fulfilled value that applies to the entire package.
habe das ausgebaut.

2022-01-28 08:40 UTC, hf-kklein commented on src/ahbicht/expressions/condition_expression_parser.py
> +    package: "[" INT "P]"
ich würde die wiederholbarkeiten #96 gerne nicht in diesem PR machen.

2022-01-28 17:03 UTC, hf-kklein commented on src/ahbicht/expressions/condition_expression_parser.py
> +        # As of now the packages are extracted separately via their rule, not by analyzing the key.
und an der stelle bricht sehr viel zusammen...

2022-01-28 17:35 UTC, hf-kklein commented on src/ahbicht/expressions/condition_expression_parser.py
> +    # Prior to the introduction of packages we could simply loop over all the 'INT' terminals and be sure that
hard to explain, ugly workaround

2022-01-28 17:37 UTC, hf-kklein commented
obsoleted by #116

2022-01-28 17:37 UTC, closed without merging